


hm:
  db:
    host: localhost       # ← 保持不变
    port: 3307            # ← 改成 Docker 映射的端口
    username: root
    password: 123
    database: hm-trade

  swagger:
    title: 订单服务接口文档
    package: com.hmall.trade.controller
