


hm:
  db:
    host: localhost       # ← 保持不变
    port: 3307            # ← 改成 Docker 映射的端口
    username: root
    password: 123
    database: hm-pay

  swagger:
    title: 支付服务接口文档
    package: com.hmall.pay.controller
